name: DSA mentions sync

on:
  push:
    branches: [ main ]

jobs:
  update-mentions:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Update DSA mentions
        run: scripts/update_dsa_mentions.py
      - name: Commit changes
        run: |
          if git diff --quiet; then
            echo "No mention updates"
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -am "chore: update DSA mentions"
            git push
